### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [vikhyat/mixtral-inference#1]
Hi,
What is the license for this space?

**Comment by vikhyat** [comment]
Same as the original Mistral repo, Apache 2.0. I'll add it to the repo shortly.

**Comment by fakerybakery** [comment]
OK, thank you!

**Comment by vikhyat** [comment]
added: https://github.com/vikhyat/mixtral-inference/commit/a6f2964b2d0e70eb2dc2848e05dbf88c6667f829
