### ISSUE TITLE
params.json not found

### ISSUE THREAD

**Issue by jimz7** [vikhyat/mixtral-inference#3]
Thanks for the great repo!
I am trying to run inference on snapshot_downloaded version of the model, but I found that I don't have this `params.json` file. I have also checked the Huggingface page for the model but still can't find such file. 

https://github.com/vikhyat/mixtral-inference/blob/9b0dc55b52c5e57e2b5309506151985b36e28d1f/mixtral/model.py#L313C1-L315C59

**Comment by vikhyat** [comment]
Hello! I'm not sure what `snapshot_downloaded` is, this was designed to run the weights format released in the torrent. I think the Huggingface weights are in a different format (key names were different IIRC). Here's the contents of params.json though:

```
{"dim": 4096, "n_layers": 32, "head_dim": 128, "hidden_dim": 14336, "n_heads": 32, "n_kv_heads": 8, "norm_eps": 1e-05, "vocab_size": 32000, "moe": {"num_experts_per_tok": 2, "num_experts": 8}}
```
